
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shrey
 */
public class StopWatch extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form StopWatch
     */
    static int x=0;
    public static newThread Gary;
    public StopWatch() {
        initComponents();
        resetButton.setVisible(false);
        lapButton.setVisible(false);
        Thread t=new Thread(this);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        stopwatchLabel = new javax.swing.JLabel();
        lapButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lapTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StopWatch");
        setForeground(java.awt.Color.black);
        setPreferredSize(new java.awt.Dimension(450, 600));
        setSize(new java.awt.Dimension(450, 600));
        getContentPane().setLayout(null);

        startButton.setBackground(new java.awt.Color(14, 10, 253));
        startButton.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        startButton.setForeground(new java.awt.Color(255, 255, 255));
        startButton.setText("Start");
        startButton.setToolTipText("Start the stopwatch");
        startButton.setName(""); // NOI18N
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startButton);
        startButton.setBounds(155, 550, 150, 50);

        resetButton.setBackground(new java.awt.Color(14, 10, 253));
        resetButton.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setText("Reset");
        resetButton.setToolTipText("Reset the stopwatch");
        resetButton.setName(""); // NOI18N
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton);
        resetButton.setBounds(0, 550, 100, 50);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(2, 30, 249));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("STOP WATCH");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 450, 50);

        dateLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(250, 66, 66));
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLabel.setToolTipText("Current Date");
        getContentPane().add(dateLabel);
        dateLabel.setBounds(200, 75, 250, 30);

        timeLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(250, 66, 66));
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setToolTipText("Current Time");
        getContentPane().add(timeLabel);
        timeLabel.setBounds(200, 105, 250, 30);

        stopwatchLabel.setFont(new java.awt.Font("Ubuntu", 0, 28)); // NOI18N
        stopwatchLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stopwatchLabel.setText("0.00");
        stopwatchLabel.setToolTipText("Stopwatch Time");
        getContentPane().add(stopwatchLabel);
        stopwatchLabel.setBounds(0, 200, 450, 75);

        lapButton.setBackground(new java.awt.Color(14, 10, 253));
        lapButton.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        lapButton.setForeground(new java.awt.Color(255, 255, 255));
        lapButton.setText("Lap");
        lapButton.setToolTipText("Take a Lap");
        lapButton.setName(""); // NOI18N
        lapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapButtonActionPerformed(evt);
            }
        });
        getContentPane().add(lapButton);
        lapButton.setBounds(350, 550, 100, 50);

        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        lapTextArea.setEditable(false);
        lapTextArea.setColumns(20);
        lapTextArea.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        lapTextArea.setRows(5);
        lapTextArea.setToolTipText("Lap Time");
        jScrollPane1.setViewportView(lapTextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 280, 450, 270);

        jLabel1.setBackground(new java.awt.Color(37, 33, 28));
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 450, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        Gary.stop();
        startButton.setText("Start");
        x=0;    
        stopwatchLabel.setText("0.00");
        lapTextArea.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_resetButtonActionPerformed

    private void lapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapButtonActionPerformed
        // TODO add your handling code here:
        lapTextArea.append("    "+stopwatchLabel.getText()+"\n");
    }//GEN-LAST:event_lapButtonActionPerformed
    
    public void setTime(int hour,int minute,int second){
        Date d=new Date();
        d.setHours(hour);
        d.setMinutes(minute);
        d.setSeconds(second);
        SimpleDateFormat sdf=new SimpleDateFormat("HH:mm:ss");
        stopwatchLabel.setText(sdf.format(d));
    }
    public void setDate(){
        GregorianCalendar manmeet=new GregorianCalendar();
        Date d=new Date(manmeet.getTimeInMillis());
        SimpleDateFormat sdf=new SimpleDateFormat("hh:mm:ss a");
        SimpleDateFormat sdf1=new SimpleDateFormat("E, dd MMMM yyyy");
//        int day=manmeet.get(Calendar.DAY_OF_MONTH);
//        int month=manmeet.get(Calendar.MONTH)+1;
//        int year=manmeet.get(Calendar.YEAR);
        dateLabel.setText(sdf1.format(d));
//        int hour=manmeet.get(Calendar.HOUR);
//        int minute=manmeet.get(Calendar.MINUTE);
//        int second=manmeet.get(Calendar.SECOND);
        timeLabel.setText(sdf.format(d));
    }
    
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if(newThread.z==0)
            new newThread("Time");
        if(x==0){
            Gary=new newThread("Abhey");
            x=1;
            startButton.setText("Pause");
            startButton.setToolTipText("Pause the stopwatch");
        }
        else{
            if(x==1){
                Gary.Suspend();
                startButton.setText("Resume");
                startButton.setToolTipText("Resume the stopwatch");
                x=2;
            }
            else{
                startButton.setText("Pause");
                startButton.setToolTipText("Pause the stopwatch");
                Gary.Resume();
                x=1;
            }
        }
        resetButton.setVisible(true);
        lapButton.setVisible(true);
       // TODO add your handling code here:
    }//GEN-LAST:event_startButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Dracula".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StopWatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StopWatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StopWatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StopWatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StopWatch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lapButton;
    private javax.swing.JTextArea lapTextArea;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel stopwatchLabel;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(true)
        this.setDate();//To change body of generated methods, choose Tools | Templates.
    }
}
